// MORGUNMVON Product Library
// Keep every value between quotation marks. See README.md before editing.
const PRODUCT_LIBRARY = [
  {
    productId: "Philadelphia-13",
    collection: "Personalized Football Pillows",
    productType: "Football Pillow Cover",
    designId: "Philadelphia-13",
    primaryColor: "TBD",
    secondaryColor: "TBD",
    material: "Polyester short plush",
    shape: "Square",
    printType: "Double-sided print",
    customizationType: "Custom Name + Number",
    availableSizes: "12, 14, 16, 18, 20, 22, 24, 26 inches",
    productImage: "",
  },
  {
    productId: "Philadelphia-14",
    collection: "Personalized Football Pillows",
    productType: "Football Pillow Cover",
    designId: "Philadelphia-14",
    primaryColor: "TBD",
    secondaryColor: "TBD",
    material: "Polyester short plush",
    shape: "Square",
    printType: "Double-sided print",
    customizationType: "Custom Name + Number",
    availableSizes: "12, 14, 16, 18, 20, 22, 24, 26 inches",
    productImage: "",
  },
  {
    productId: "Philadelphia-15",
    collection: "Personalized Football Pillows",
    productType: "Football Pillow Cover",
    designId: "Philadelphia-15",
    primaryColor: "TBD",
    secondaryColor: "TBD",
    material: "Polyester short plush",
    shape: "Square",
    printType: "Double-sided print",
    customizationType: "Custom Name + Number",
    availableSizes: "12, 14, 16, 18, 20, 22, 24, 26 inches",
    productImage: "",
  },
  {
    productId: "Philadelphia-16",
    collection: "Personalized Football Pillows",
    productType: "Football Pillow Cover",
    designId: "Philadelphia-16",
    primaryColor: "TBD",
    secondaryColor: "TBD",
    material: "Polyester short plush",
    shape: "Square",
    printType: "Double-sided print",
    customizationType: "Custom Name + Number",
    availableSizes: "12, 14, 16, 18, 20, 22, 24, 26 inches",
    productImage: "",
  },
];
