// MORGUNMVON Product Library
// Keep every value between quotation marks. See README.md before editing.
const PRODUCT_LIBRARY = [
  {
    productId: "Philadelphia-13",
    collection: "Philadelphia",
    productType: "Decorative panel",
    style: "Architectural minimalism",
    name: "Philadelphia",
    number: "13",
    primaryColor: "Warm ivory",
    secondaryColor: "Graphite",
    customizationType: "Color and size",
    productImage: "",
  },
  {
    productId: "Philadelphia-14",
    collection: "Philadelphia",
    productType: "Decorative panel",
    style: "Sculptural modern",
    name: "Philadelphia",
    number: "14",
    primaryColor: "Sand",
    secondaryColor: "Walnut",
    customizationType: "Color and finish",
    productImage: "",
  },
  {
    productId: "Philadelphia-15",
    collection: "Philadelphia",
    productType: "Decorative panel",
    style: "Contemporary geometric",
    name: "Philadelphia",
    number: "15",
    primaryColor: "Chalk white",
    secondaryColor: "Terracotta",
    customizationType: "Color and size",
    productImage: "",
  },
  {
    productId: "Philadelphia-16",
    collection: "Philadelphia",
    productType: "Decorative panel",
    style: "Quiet luxury",
    name: "Philadelphia",
    number: "16",
    primaryColor: "Stone grey",
    secondaryColor: "Brushed brass",
    customizationType: "Color, finish, and size",
    productImage: "",
  },
];
